
export const CARS = [
    { name: 'Ferrari 296 GT3', class: 'GT3' },
    { name: 'Lamborghini Huracan GT3 EVO2', class: 'GT3' },
    { name: 'Porsche 992 GT3 R', class: 'GT3' },
    { name: 'BMW M4 GT3', class: 'GT3' },
    { name: 'Audi R8 LMS GT3 evo II', class: 'GT3' },
    { name: 'McLaren 720S GT3 Evo', class: 'GT3' },
    { name: 'Mercedes-AMG GT3 Evo', class: 'GT3' },
    { name: 'Aston Martin V8 Vantage GT3', class: 'GT3' },
    { name: 'Honda NSX GT3 Evo', class: 'GT3' },
    { name: 'Nissan GT-R Nismo GT3 (2018)', class: 'GT3' },
    { name: 'Bentley Continental GT3 (2018)', class: 'GT3' },
    { name: 'Lexus RC F GT3', class: 'GT3' },
    { name: 'Alpine A110 GT4', class: 'GT4' },
    { name: 'Aston Martin Vantage AMR GT4', class: 'GT4' },
    { name: 'Audi R8 LMS GT4', class: 'GT4' },
    { name: 'BMW M4 GT4', class: 'GT4' },
    { name: 'Chevrolet Camaro GT4.R', class: 'GT4' },
    { name: 'Ginetta G55 GT4', class: 'GT4' },
    { name: 'KTM X-Bow GT4', class: 'GT4' },
    { name: 'Maserati MC GT4', class: 'GT4' },
    { name: 'McLaren 570S GT4', class: 'GT4' },
    { name: 'Mercedes-AMG GT4', class: 'GT4' },
    { name: 'Porsche 718 Cayman GT4 Clubsport', class: 'GT4' },
];

export const TRACKS = [
    'Barcelona',
    'Brands Hatch',
    'Circuit of the Americas (COTA)',
    'Donington Park',
    'Hungaroring',
    'Indianapolis',
    'Imola',
    'Kyalami',
    'Laguna Seca',
    'Misano',
    'Monza',
    'Mount Panorama (Bathurst)',
    'Nürburgring',
    'Oulton Park',
    'Paul Ricard',
    'Red Bull Ring',
    'Silverstone',
    'Snetterton',
    'Spa-Francorchamps',
    'Suzuka',
    'Valencia',
    'Watkins Glen',
    'Zandvoort',
    'Zolder',
];

export const DRIVING_STYLES = [
    'Kiegyensúlyozott (Biztonságos alapbeállítás)',
    'Agresszív (Túlkormányzottságra hajlamos)',
    'Stabil (Alulkormányzottságra hajlamos)',
    'Versenyre optimalizált (Gumikímélő)',
    'Időmérőre optimalizált (Maximális tapadás)',
];
